[build]
builder = "nixpacks"

[deploy]
startCommand = "deno task serve"

[services.variables]
PORT = "${{ PORT }}"
MONGODB_URI = "${{ MONGODB_URI }}"
JWT_SECRET = "${{ JWT_SECRET }}"
MONGO_USERNAME = "${{ MONGO_USERNAME }}"
MONGO_PASSWORD = "${{ MONGO_PASSWORD }}"
MONGO_CLUSTER = "${{ MONGO_CLUSTER }}"
DB_NAME = "${{ DB_NAME }}"
