[build]
builder = "dockerfile"
dockerfilePath = "BosserP05/Dockerfile"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[[services]]
name = "backend"
source = "BosserP05"

[services.variables]
PORT = "8000"
MONGODB_URI = "${{ MONGODB_URI }}"
