[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

# [deploy] - Comentado para deshabilitar healthcheck
# healthcheckPath = "/health"
# healthcheckTimeout = 300
# restartPolicyType = "on_failure"

[services.variables]
PORT = "${{ PORT }}"
MONGODB_URI = "${{ MONGODB_URI }}"
JWT_SECRET = "${{ JWT_SECRET }}"
MONGO_USERNAME = "${{ MONGO_USERNAME }}"
MONGO_PASSWORD = "${{ MONGO_PASSWORD }}"
MONGO_CLUSTER = "${{ MONGO_CLUSTER }}"
DB_NAME = "${{ DB_NAME }}"
